### PR TITLE
FrozenLib & Wilder Wild compatibility

### LINKED ISSUE #40: FrozenLib (Ex Wilder Wild) Incompatibility
### Mod Name

Wilder Wild

### Mod Homepage

https://modrinth.com/mod/wilder-wild

### Describe the bug

Crash on start up.

### Steps to reproduce

_No response_

### Logs

https://pastebin.com/pg7rRWPw

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Treetrain1**
For implementation, I added a new method transformation. It is just a copy of `ModifyInjectionPoint` with ordinal support. I submitted a PR to Adapter for this, can be replaced with the content from that PR when merged.
Closes #40 
Also fixes compatibility with Configurable Everything and newer versions of Simple Copper Pipes

Works with Wilder Wild 2.1.10+
For the most part works, only compatibility issue left is the ModifyArgs lvt patch thingy

### CODE REVIEW

**Comment by Treetrain1** [comment]
so far I’ve gotten rid of the issue in #40 but there’s still other existing compatibility issues
Ex
WW uses a `ModifyArgs` in `LiquidBlockRenderer.tesselate` on `LiquidBlockRenderer.vertex`
I believe it just has one more float parameter, `alpha` somewhere around index 7 (idk for sure)

I am not very familiar with patches. Is there anything that can patch this?

**Comment by Su5eD** [comment]
What is the exact error? Adapter should be able to handle simple LVT changes

**Comment by Treetrain1** [comment]
> What is the exact error? Adapter should be able to handle simple LVT changes

heres ww source for reference
```java
@ModifyArgs(method = "tesselate", at = @At(value = "INVOKE", target = "Lnet/minecraft/client/renderer/block/LiquidBlockRenderer;vertex(Lcom/mojang/blaze3d/vertex/VertexConsumer;DDDFFFFFI)V", ordinal = 8))
	private void wilderWild$sideTextureBottom1(Args args) {
		if (this.wilderWild$isWater) {
			this.wilderWild$u0 = this.waterOverlay.getU0();
			this.wilderWild$u1 = this.waterOverlay.getU1();
			this.wilderWild$v0 = this.waterOverlay.getV0();
			this.wilderWild$v1 = this.waterOverlay.getV1();
			args.set(7, this.wilderWild$u0);
			args.set(8, this.wilderWild$v1);
		}
	}
```

here
its not very descriptive though
```
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at net.minecraft.client.renderer.block.BlockRenderDispatcher.<init>(BlockRenderDispatcher.java:41) ~[forge-1.20.1-47.1.3_mapped_official_1.20.1-recomp.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:fabric-resource-loader-v0.client.mixins.json:KeyedResourceReloadListenerClientMixin from mod (unknown),pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:499) ~[forge-1.20.1-47.1.3_mapped_official_1.20.1-recomp.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:182) ~[forge-1.20.1-47.1.3_mapped_official_1.20.1-recomp.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.3.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.3.jar:?] {}
	at net.minecraftforge.fml.loading.targets.ForgeClientUserdevLaunchHandler.devService(ForgeClientUserdevLaunchHandler.java:19) ~[fmlloader-1.20.1-47.1.3.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonDevLaunchHandler.lambda$makeService$7(CommonDevLaunchHandler.java:135) ~[fmlloader-1.20.1-47.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Multi-argument modifier method wilderWild$sideTextureBottom1(Lorg/spongepowered/asm/mixin/injection/invoke/arg/Args;)V in wilderwild.mixins.json:client.general.LiquidBlockRendererMixin from mod (unknown) failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins.wilderwild.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	... 32 more```

**Comment by Treetrain1** [comment]
Any idea on how something like this could be fixed?

**Comment by Treetrain1** [comment]
actually
the lvt changes arent getting applied probably because its a `ModifyArgs`

i believe this is going to require `ModifyArgs` to be handled in the lvt patch you were referring to

**Comment by Treetrain1** [comment]
Using [this build](https://cdn.discordapp.com/attachments/978318121154777149/1163250140149186670/WilderWild-2.1.7-Fabric1.20.1.jar?ex=653ee41d&is=652c6f1d&hm=19253665ac57dc049bd5e8f84d205380c04c5bd88a7fc37eff43c9e48f416549&)
its able to get in game, but crashes when opening the inventory

that build is the same just with that renderer mixin disabled

```
net.minecraftforge.fml.ModLoadingException: Fabric Item Group API (v1) (fabric_item_group_api_v1) encountered an error during the done event phase
�7java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.ItemLike.asItem()" because "anchor" is null
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:111) ~[javafmllanguage-1.20.1-47.1.3.jar:?] {}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$29(ModLoader.java:326) ~[fmlcore-1.20.1-47.1.3.jar:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:227) ~[fmlcore-1.20.1-47.1.3.jar:?] {}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:326) ~[fmlcore-1.20.1-47.1.3.jar:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onCreativeModeTabBuildContents(ForgeHooksClient.java:1212) ~[forge-1.20.1-47.1.3_mapped_official_1.20.1-recomp.jar:?] {re:mixin,re:classloading,pl:mixin:APP:connectormod.mixins.json:ForgeHooksClientMixin from mod (unknown),pl:mixin:A}
	at net.minecraft.world.item.CreativeModeTab.buildContents(CreativeModeTab.java:129) ~[forge-1.20.1-47.1.3_mapped_official_1.20.1-recomp.jar:?] {re:classloading,pl:accesstransformer:B,xf:fml:connectormod:injectCreativeModeTabCtr,re:mixin,pl:accesstransformer:B,xf:fml:connectormod:injectCreativeModeTabCtr}
	at net.minecraft.world.item.CreativeModeTabs.lambda$buildAllTabContents$50(CreativeModeTabs.java:1696) ~[forge-1.20.1-47.1.3_mapped_official_1.20.1-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?] {re:mixin}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraft.world.item.CreativeModeTabs.buildAllTabContents(CreativeModeTabs.java:1695) ~[forge-1.20.1-47.1.3_mapped_official_1.20.1-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.item.CreativeModeTabs.tryRebuildTabContents(CreativeModeTabs.java:1710) ~[forge-1.20.1-47.1.3_mapped_official_1.20.1-recomp.jar:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen.<init>(CreativeModeInventoryScreen.java:86) ~[forge-1.20.1-47.1.3_mapped_official_1.20.1-recomp.jar:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:connectormod.mixins.json:CreativeModeInventoryScreenMixin from mod (unknown),pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.InventoryScreen.init(InventoryScreen.java:48) ~[forge-1.20.1-47.1.3_mapped_official_1.20.1-recomp.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.init(Screen.java:321) ~[forge-1.20.1-47.1.3_mapped_official_1.20.1-recomp.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabric-screen-api-v1.mixins.json:ScreenAccessor from mod (unknown),pl:mixin:APP:fabric-screen-api-v1.mixins.json:ScreenMixin from mod (unknown),pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.setScreen(Minecraft.java:1007) ~[forge-1.20.1-47.1.3_mapped_official_1.20.1-recomp.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.handleKeybinds(Minecraft.java:1928) ~[forge-1.20.1-47.1.3_mapped_official_1.20.1-recomp.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.tick(Minecraft.java:1795) ~[forge-1.20.1-47.1.3_mapped_official_1.20.1-recomp.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1112) ~[forge-1.20.1-47.1.3_mapped_official_1.20.1-recomp.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.run(Minecraft.java:718) ~[forge-1.20.1-47.1.3_mapped_official_1.20.1-recomp.jar:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-1.20.1-47.1.3_mapped_official_1.20.1-recomp.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.3.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.3.jar:?] {}
	at net.minecraftforge.fml.loading.targets.ForgeClientUserdevLaunchHandler.devService(ForgeClientUserdevLaunchHandler.java:19) ~[fmlloader-1.20.1-47.1.3.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonDevLaunchHandler.lambda$makeService$7(CommonDevLaunchHandler.java:135) ~[fmlloader-1.20.1-47.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.ItemLike.asItem()" because "anchor" is null
	at net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroupEntries.addBefore(FabricItemGroupEntries.java:462) ~[fabric-item-group-api-v1-4.0.11+369cb3a477.jar%23255!/:4.0.11+369cb3a477] {re:classloading}
	at net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroupEntries.addBefore(FabricItemGroupEntries.java:323) ~[fabric-item-group-api-v1-4.0.11+369cb3a477.jar%23255!/:4.0.11+369cb3a477] {re:classloading}
	at net.frozenblock.lib.item.api.FrozenCreativeTabs.lambda$addBefore$1(FrozenCreativeTabs.java:74) ~[WilderWild-2.1.7-Fabric+1.20.1$frozenlib-1.3.12-mc1.20.1_mapped_mcp_1.20.1.jar%23306!/:?] {re:classloading}
	at net.fabricmc.fabric.impl.itemgroup.ItemGroupEventsImpl.lambda$createModifyEvent$1(ItemGroupEventsImpl.java:53) ~[fabric-item-group-api-v1-4.0.11+369cb3a477.jar%23255!/:4.0.11+369cb3a477] {re:classloading}
	at net.fabricmc.fabric.impl.itemgroup.ItemGroupEventsImpl.onCreativeModeTabBuildContents(ItemGroupEventsImpl.java:80) ~[fabric-item-group-api-v1-4.0.11+369cb3a477.jar%23255!/:4.0.11+369cb3a477] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.5.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.5.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.20.1-47.1.3.jar:?] {}
	... 44 more
```

**Comment by Treetrain1** [comment]
was able to just fix all the errors in frozenlib and wilder wild themselves

although
the modify args thing will still need to be fixed, but i just set it to not crash the game

**Comment by Treetrain1** [comment]
only works with WW 2.1.7+
gameplay should be fine

screenshot of wilder wild + cracker's wither storm mod
image

**Comment by Treetrain1** [comment]
actually theres one issue left
ill fix it tmr

**Comment by Treetrain1** [comment]
seems somewhat simple to fix
should just be an easy param addition
```
[15Oct2023 22:34:43.031] [Render thread/WARN] [mixin/]: Injection warning: LVT in net/minecraft/server/level/ServerPlayerGameMode::m_7179_(Lnet/minecraft/server/level/ServerPlayer;Lnet/minecraft/world/level/Level;Lnet/minecraft/world/item/ItemStack;Lnet/minecraft/world/InteractionHand;Lnet/minecraft/world/phys/BlockHitResult;)Lnet/minecraft/world/InteractionResult; has incompatible changes at opcode 126 in callback mixin/frozenlib.tag.mixins.json:ServerPlayerGameModeMixin from mod (unknown)->@Inject::frozenLib$useItemOn(Lnet/minecraft/server/level/ServerPlayer;Lnet/minecraft/world/level/Level;Lnet/minecraft/world/item/ItemStack;Lnet/minecraft/world/InteractionHand;Lnet/minecraft/world/phys/BlockHitResult;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;Z)V.
 Expected: [Lnet/minecraft/core/BlockPos;, Lnet/minecraft/world/level/block/state/BlockState;, Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;, Z]
    Found: [Lnet/minecraft/core/BlockPos;, Lnet/minecraft/world/level/block/state/BlockState;, Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;, Lnet/minecraft/world/item/context/UseOnContext;]
Available: [Lnet/minecraft/core/BlockPos;, Lnet/minecraft/world/level/block/state/BlockState;, Lnet/minecraftforge/event/entity/player/PlayerInteractEvent$RightClickBlock;, Lnet/minecraft/world/item/context/UseOnContext;, Z]
```

**Comment by Su5eD** [comment]
Hm, that should get automatically patched by adapter, I'll see what's wrong there

**Comment by Su5eD** [comment]
Okay, I tested running Wilder Wild version 2.1.9 on the latest Connector dev build, and I've run into the frozenlib `AxeItem` mixin conflict plus a registry freeze bug in Connector, which has now been fixed. So in the end, the only remaining conflict is the `AxeItem` mixin. Could you try again using the latest revision?

**Comment by murao-kun** [comment]
I tested newest changes with WW 2.1.9 and adapter pull request done by Treetrain1 and seems like it is working just fine. There is no issue with AxeItem mixin.

**Comment by Treetrain1** [comment]
So far my testing results are great, but I’d like to do further testing before this is merged.
I’ve implemented a mixin config in a work in progress version of Wilder Wild and have refactored a lot of mixins, so I want to make sure this also works with that version just in case it for some reason doesn’t.
It *should* still work but I want to be 100% sure.
I’ll mark this PR as ready for review once I’ve tested and released that version.

**Comment by Treetrain1** [comment]
Works with the latest version of Wilder Wild (2.1.10)!

**Comment by Treetrain1** [comment]
i believe this is in a merge ready state
up to you ig

**Comment by Su5eD** [comment]
Thanks for taking care of this on your side as well. I've tried running Wilder Wild on the current version of connector, and it seems like it work out of the box. Is the patch to `AxeItem`'s mixin still necessary in that case?

**Comment by Treetrain1** [comment]
> Thanks for taking care of this on your side as well. I've tried running Wilder Wild on the current version of connector, and it seems like it work out of the box. Is the patch to `AxeItem`'s mixin still necessary in that case?

Oh, that's strange
I feel like that patch may still be necessary
because i havent seen anything that could automatically fix the ordinal of the injection point

**Comment by Su5eD** [comment]
Hm, I have an idea on how to patch that dynamically, though it relies on having access to unpatched mc files, which shouldn't be a problem in forge.

**Comment by Su5eD** [comment]
Okay that should do. I've added a dynamic patch that can analyze all method calls for the `@At` target and correct the injection point ordinal based on the target's surrounding instructions, eliminating the need to add a hardcoded patch with a fixed number offset.

I believe the modifyargs mixins you've mentioned still need fixing though.

**Comment by Treetrain1** [comment]
> Okay that should do. I've added a dynamic patch that can analyze all method calls for the `@At` target and correct the injection point ordinal based on the target's surrounding instructions, eliminating the need to add a hardcoded patch with a fixed number offset.
> 
> I believe the modifyargs mixins you've mentioned still need fixing though.

i dont think that works with the axe item mixin
either that or it causes another issue that causes the game to crash
it just crashes after this point now
image

**Comment by Su5eD** [comment]
Sorry, seems like registry bootstrap/freeze timing got messed up again. Can you try using [this](https://github.com/Sinytra/Connector/actions/runs/6615427200) dev build?

**Comment by Treetrain1** [comment]
Fully works in beta 21
I'll close this PR now that its fixed

**Comment by Su5eD** [comment]
Nice, thanks for fixing some of the issues on your end as well, appreciated!

**Comment by No1129** [comment]
i like how the same day this was fixed wilder wilds updated and that update does not work with connector
:|

**Pull request closed without merging**
