### PR TITLE
Fix loading on servers

### PR DESCRIPTION
**Pull request by dima-dencep**
## The Issue
The connector prevents the server from starting

## The Proposal
Fix the issue above

### CODE REVIEW

**Comment by Su5eD** [comment]
Have you tested this? I'm getting the following error when running on a neoforge 21.1.51 dedicated server

> Exception message: java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because the return value of "net.neoforged.neoforge.registries.DataPackRegistriesHooks.getDataPackRegistries()" is null

**Comment by dima-dencep** [comment]
> Have you tested this?

Of course
https://mclo.gs/AqxBxY0

**Comment by Mattabase** [comment]
> > Have you tested this?
> 
> Of course https://mclo.gs/AqxBxY0

I am getting the same error as Su5eD when running on a neoforge 21.1.51 dedicated serve

**Comment by dima-dencep** [comment]
I don't get this error

**Comment by dima-dencep** [comment]
I don't know, maybe OS is the reason?

**Comment by wc7086** [comment]
@dima-dencep Can you give me a copy of the binary file?

**Comment by dima-dencep** [comment]
Compile it yourself

**Comment by wc7086** [comment]
This fix won't work for me
https://mclo.gs/xBJtTo6

**Comment by Su5eD** [comment]
>  **** FAILED TO BIND TO PORT!
> Perhaps a server is already running on that port?

This seems like an unrelated issue

**Comment by wc7086** [comment]
> > **** FAILED TO BIND TO PORT!
> > Perhaps a server is already running on that port?
> 
> This seems like an unrelated issue

Sorry, because I don't have online-mode enabled there is always a warning that I subconsciously ignore.

**Pull request merged**
