### PR TITLE
Try to adapt map type changes.

### PR DESCRIPTION
**Pull request by melontini**
As mentioned here: https://github.com/Sinytra/Connector/issues/29#issuecomment-1675967198, some map fields have had their type changed by Forge.

This only tackles ParticleEngine, BlockColors and ItemColors as they have proper registration methods and should cause the least problems.

Here's what we do:
1. Add a new field of the original type.
2. Add a public getter for this field.
3. In this getter, we check if new entries have been added to the original map and add them to the new map. 
   * Also throw an exception if some mod tries to add new entries to the connector map. It might be a good idea to add new entries to the exception.
4. We remap mods to use the new getter using FieldToMethodTransformer.

I'm not sure if this is a good solution. It should* be faster than converting the entire map on each call, and less complex than remapping mods to the new map type. This may also be an edge case, as I only know of 1 mod that accesses ParticleEngine.providers, and I made it.

I also moved REPLACEMENTS to ImmutableMap.Builder because Map.of() ran out of parameters.

### CODE REVIEW

**Comment by Su5eD** [comment]
I remember having a similar bridge in the early days of connector before the creation of FFAPI. My approach was creating a custom `IdMap` implementation that would redirect calls to registries for getting IDs. It might be a slightly more efficient solution compared to recomputing the `IdMap` every time its backing `Map` changes. What do you think?

**Comment by melontini** [comment]
I also thought about this. This should be faster than recomputing the map + it will support writing to those maps. 

I didn't go with because it would require reimplementing 3 Map types and in the case of factories writing is not really needed. (`IdMapper`, `Map<Key, KeyBinding>`, `Int2ObjectMap<ParticleFactory<?>>`). Although, for maps, it's possible to pass a `java.lang.reflect.Proxy` instance, but this might be unreliable.

**Comment by Su5eD** [comment]
Can a redirector be applied in the ParticleEngine as well?

**Comment by melontini** [comment]
Yup, I just wanted to make a comment, but forgot to. 😅

There's currently an issue with the `byId` method. Mojang made it final and I can't override it. 

And for `Int2ObjectMap`, I'm not sure how to implement `keySet`, `entrySet`, and iterators. By contract, they have to be able to modify the map, but they also need to be converted from int to Reference. Should I add some sort of `ConvertingIntSet`, return a set which doesn't modify the map, or throw an `UnsupportedOperationException`?

**Comment by Su5eD** [comment]
Look much better, I'll run some tests and it should be good to go.

**Comment by Su5eD** [comment]
I'm getting a NullPointerException when testing the bridge with the following code:
```java
public class BridgeTest implements ModInitializer {
    private static final Logger LOGGER = LogUtils.getLogger();

    @Override
    public void onInitialize() {
        ClientLifecycleEvents.CLIENT_STARTED.register(client -> {
            int grassBlockID = Registries.BLOCK.getRawId(Blocks.GRASS_BLOCK);
            LOGGER.info("Block color for grass: {}", client.getBlockColors().providers.get(grassBlockID));

            int potionID = Registries.ITEM.getRawId(Items.POTION);
            LOGGER.info("Item color for potion: {}", client.itemColors.providers.get(potionID));

            int dustParticleTypeID = Registries.PARTICLE_TYPE.getRawId(ParticleTypes.DUST);
            LOGGER.info("Particle factory for dust particle type: {}", client.particleManager.factories.get(dustParticleTypeID));
        });
    }
}
```

Looks like the redirecting maps are being initialized before the backing map, resulting in the passed constructor argument being null. Does it work for you? Are there any mods that directly access these fields?

**Comment by melontini** [comment]
This is embarrassing. I tested the original impl, but along with the comment, forgot to test the new one...

Anyway, you're right, the mixin moved the assignment of the "registry" field to after the redirect field. Easy fix.

As for usage, I'm aware of 2 mods that use these fields: my own Dark Matter and [Colormatic](https://github.com/kvverti/colormatic/blob/master/src/client/java/io/github/kvverti/colormatic/mixin/model/ModelLoaderMixin.java). Although in the case of Dark Matter, I switched to ThreadLocal and ModifyExpressionValue. Pretty low hit rate, so this may not be necessary.

**Review by Su5eD — APPROVED** [review]

**Pull request merged**
